<?php
/** @var \Homework\Model\Student $student */

$title = 'Delete student';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($student->firstName); ?> <?php echo $this->escapeHtml($student->lastName); ?>'?
</p>
<?php
$url = $this->url('student', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $student->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>