<?php

$title = 'Students';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('student', array('action'=>'add'));?>">Add new student</a>
</p>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Avg Grade</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($students as $student) : ?>
    <tr>
        <td><?php echo $student['id'];?></td>
        <td><?php echo $this->escapeHtml( $student['first_name'].' '.$student['last_name'] );?></td>
        <td><?php echo round( $student['avgGrade'],1 );?></td>
        <td>
            <a href="<?php echo $this->url('student',
                array('action'=>'edit', 'id' => $student['id']));?>">Edit</a>
            <a href="<?php echo $this->url('student',
                array('action'=>'delete', 'id' => $student['id']));?>">Delete</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>