<?php

$title = 'Edit grade';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'grade',
    array(
        'action' => 'edit',
        'student_id'     => $this->student_id,
        'homework_id'     => $this->homework_id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('homework_id'));
echo $this->formHidden($form->get('student_id'));
echo $this->formRow($form->get('grade'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();